name: Quality Checks

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check-linux:
    name: Rust Quality Checks (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: linux
      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test

  check-windows:
    name: Windows Build Checks
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          cache-key: windows
      - name: Test
        run: cargo test
      - name: Check minimal example
        run: cargo check --manifest-path examples/minimal-dll/Cargo.toml
      - name: Check lifecycle example
        run: cargo check --manifest-path examples/lifecycle-dll/Cargo.toml
